---
title: "dataAnalysis_comb"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#package
```{r}
library(tidyr)
library(dplyr)
library(ggplot2)
library(Rmisc)
library(reshape2)
library(effectsize)
library(data.table)
library(bruceR)
library(ggpubr)
library(lmerTest)
set.seed(2)
```

#loading
```{r}
load("exp2.Rda")
df.final$mycondition=factor(df.final$mycondition,levels = c("regular","irregular"))
df1=df.final %>% mutate(exp="exp2",choice=NULL)
df1.link=df1%>%select("subject","acc_a","A_pro","mycondition","exp")%>%mutate(acc=acc_a,pro=A_pro,acc_a=NULL,A_pro=NULL) %>% 
  rbind(df1%>%select("subject","acc_b","B_pro","mycondition","exp")%>%mutate(acc=acc_b,pro=B_pro,acc_b=NULL,B_pro=NULL)) %>%
  summarySE(measurevar = "acc",groupvars = c("subject","mycondition","exp"))
df1.device=df1%>% summarySE(measurevar = "acc_device",groupvars = c("subject","mycondition","exp"))

load("exp3.Rda")
df.final$mycondition=factor(df.final$mycondition,levels = c("regular","irregular"))
df2=df.final %>% subset(trial_order<10) %>% mutate(exp="exp3")
df2wog=df.final %>% subset(trial_order>=10) %>% mutate(exp="exp3")
df2.link=df2%>% select("subject","acc_a","A_pro","mycondition","exp")%>%mutate(acc=acc_a,pro=A_pro,acc_a=NULL,A_pro=NULL) %>% 
  rbind(df2 %>% select("subject","acc_b","B_pro","mycondition","exp")%>%mutate(acc=acc_b,pro=B_pro,acc_b=NULL,B_pro=NULL)) %>%
  summarySE(measurevar = "acc",groupvars = c("subject","mycondition","exp"))
df2.device=df2%>% subset(trial_order<10) %>% summarySE(measurevar = "acc_device",groupvars = c("subject","mycondition","exp"))
```

```{r}
#add more information for df.comb
df.comb=rbind(df1,df2) %>% 
  mutate(uni_label=paste(exp,seed,trial_type,mycondition,sep = "_"),
         uni_seed=paste(exp,seed,sep="_"),
         choice=paste(A_state,B_state,sep=""),
         uni_stiset=paste(exp,mystiset,sep="_"))

load("eff_exp2.Rda")
seedeff1=seed.eff
load("eff_exp3.Rda")
df.seedeff=rbind(seedeff1,seed.eff)%>% select(eff,uni_label)

df.comb=df.comb %>% merge(df.seedeff,by="uni_label")

ordlist=list("exp2"=c("AAABBB","ABABAB","AABBAB",
                      "ABBABA","AABABB","ABABBA",
                      "ABBAAB","ABAABB","ABBBAA",
                      "BAAABB","BAABAB","BABAAB",
                      "BBBAAA","BBBAAA","BBAAAB",
                      "BBABAA","BABBAA","BABABA"),
              "exp3"=c("ABABAB","BBAABA","BBBAAA",
                       "AABBAB","BABABA","BAABAB",
                       "ABAABB","AAABBB","BABBAA"))

ordlevel=data.frame(lev=0,itv=c("ABABAB","BABABA"))%>%
  rbind(data.frame(lev=1,itv=c("ABABBA","BABAAB","ABBABA","BAABAB")))%>%
  rbind(data.frame(lev=2,itv=c("ABAABB","BABBAA","AABBAB","BBAABA","AABABB","BBABAA","ABBAAB","BAABBA")))%>%
  rbind(data.frame(lev=3,itv=c("ABBBAA","AABBBA","BAAABB","BBAAAB")))%>%
  rbind(data.frame(lev=4,itv=c("AAABBB","BBBAAA")))
          
df.ord=data.frame(uni_seed=c(paste("exp2",1:18,sep="_"),paste("exp3",1:9,sep="_")))%>% 
  mutate(itv=NA,order_all=NA,order_a=NA,order_b=NA)
for (k in 1:nrow(df.ord)){
  if (k>18){o=ordlist[["exp3"]][k-18]}else{o=ordlist[["exp2"]][k]}
  df.ord$itv[k]=o
  df.ord$order_all[k]=ordlevel$lev[ordlevel$itv==o]
  df.ord$order_a[k]=sum(diff(which(unlist(strsplit(o,""))=="A"))==1)
  df.ord$order_b[k]=sum(diff(which(unlist(strsplit(o,""))=="B"))==1)
}

df.comb=df.comb%>% merge(df.ord,by="uni_seed")
```

#add model prediction
```{r}
mySim<-function(pr,amp=10){
  md=data.frame()
  for (k in unique(md.comb$uni_label)){
    d=md.comb%>% subset(uni_label==k)
    df=subset(d,select = c("seed","trial_type","mycondition","exp","uni_seed","uni_label"))%>%
      mutate(A_pro=substr(trial_type,1,1),B_pro=substr(trial_type,2,2))
    df=df[rep(1,d$ppl[1]*amp),]
    df$choice=sample(d$choice,size=d$ppl[1]*amp,prob=d[,pr],replace = T)
    df=df%>%mutate(A_state=substr(choice,1,1),B_state=substr(choice,2,2))
    md=rbind(md,df)
  }
  return(md)
}

load("mdall_exp2.Rda")
md1=mdall %>% mutate(exp="exp2",uni_seed=paste(exp,seed,sep="_"),
                     uni_label=paste(uni_seed,trial_type,mycondition,sep = "_"))
load("mdall_exp3.Rda")
md2=mdall %>% mutate(exp="exp3",uni_seed=paste(exp,seed,sep="_"),
                     uni_label=paste(uni_seed,trial_type,mycondition,sep = "_"))%>%
  subset(select=colnames(md1))
md.comb=rbind(md1,md2) %>% mutate(ppl=0)
for (k in unique(md.comb$uni_label)){
  md.comb$ppl[md.comb$uni_label==k]=sum(df.comb$uni_label==k)
}

md.nor=mySim("nor")
# md.nor_mis=mySim("nor_mis")
md.feai=mySim("fea_i")
# md.feai_mis=mySim("fea_i_mis")
md.feaw=mySim("fea_w4")
# md.feaw_mis=mySim("fea_w4_mis")
md.sim=list("nor"=md.nor,"feai"=md.feai,"feaw"=md.feaw)


#add more information
for (k in 1:length(md.sim)){
  md.sim[[k]]=md.sim[[k]]%>%
    mutate(mycondition=factor(mycondition,levels=c("regular","irregular")),
           acc_a=as.numeric(A_state==A_pro),
           acc_b=as.numeric(B_state==B_pro))%>%
    merge(df.seedeff,by="uni_label") %>% merge(df.ord,by="uni_seed")
  # %>%
  #   merge(subset(df.comb,select=c("uni_label","uni_stiset"),by="uni_label"))
}
# save(md.sim,md.nor,md.feai,md.feaw,file="md.sim.Rda")
# load("md.sim.Rda")
```

#model accuracy
```{r}
md.nor$acc_mean=(md.nor$A_state==md.nor$A_pro)*0.5+(md.nor$B_state==md.nor$B_pro)*0.5
summarySE(md.nor,measurevar = "acc_mean",groupvars = c("exp","mycondition"))

md.feaw$acc_mean=(md.feaw$A_state==md.feaw$A_pro)*0.5+(md.feaw$B_state==md.feaw$B_pro)*0.5
summarySE(md.feaw,measurevar = "acc_mean",groupvars = c("exp","mycondition"))

md.feai$acc_mean=(md.feai$A_state==md.feai$A_pro)*0.5+(md.feai$B_state==md.feai$B_pro)*0.5
summarySE(md.feai,measurevar = "acc_mean",groupvars = c("exp","mycondition"))
```

#experiment difference
```{r}
df=rbind(df1.link,df2.link)
t.test(acc~exp,subset(df,mycondition=="regular"),var.equal = T)
t.test(acc~exp,subset(df,mycondition=="irregular"),var.equal = T)
```

```{r}
df=rbind(df1.device,df2.device)
t.test(acc_device~exp,subset(df,mycondition=="regular"),var.equal = T)
t.test(acc_device~exp,subset(df,mycondition=="irregular"),var.equal = T)
```

#link-level differences
```{r}
myF1<-function(d,l){
  rec=nrow(subset(d,pro==l&state==l))/nrow(subset(d,pro==l))
  pre=nrow(subset(d,pro==l&state==l))/nrow(subset(d,state==l))
  return(list(rec,pre,2*(rec*pre)/(rec+pre)))
}
```

##link-types
```{r}
df.link=df.comb %>% mutate(pro=A_pro,state=A_state)%>%
  rbind(df.comb %>% mutate(pro=B_pro,state=B_state))

df.f1=data.frame() 
for (k in unique(df.comb$subject)){
  df=data.frame(subject=k,state=c("G","N","P"),f1=NA,rec=NA,pre=NA)
  d=df.link[df.link$subject==k,]
  df=df %>% mutate(mycondition=d$mycondition[1],exp=d$exp[1])
  for (m in 1:nrow(df)){
    re=myF1(d,df$state[m])
    df$rec[m]=re[[1]];df$pre[m]=re[[2]];df$f1[m]=re[[3]]
  }
  df.f1=rbind(df.f1,df)
}

summarySE(df.f1,measurevar ="f1",groupvars = c("mycondition","state"),na.rm=T)

df.f1.wide=df.f1 %>% reshape2:: dcast(subject+mycondition+exp~ state,value.var = "f1") %>% rename(replace = c("G" = "S1","N" = "S2","P" ="S3"))

df.f1.wide %>% 
  MANOVA(dvs="S1:S3", dvs.pattern="S(.)",between=c("mycondition"),within=c("S")) %>%
  EMMEANS("S")

```

```{r}
# t0=Sys.time()
df.mdf1=data.frame()
for (k in 1:length(md.sim)){
  df=data.frame(md=names(md.sim)[k],
    mycondition=factor(c("regular","irregular")),
    state=rep(c("G","N","P"),each=2)
  )
  for (m in 1:nrow(df)){
    d1=md.sim[[k]] %>% subset(mycondition==as.character(df$mycondition[m]))
    d=d1%>%mutate(pro=A_pro,state=A_state)%>%
      rbind(d1%>%mutate(pro=B_pro,state=B_state))
    re=myF1(d,df$state[m])
    df$rec[m]=re[[1]];df$pre[m]=re[[2]];df$f1[m]=re[[3]]
  }
  df.mdf1=rbind(df.mdf1,df)
}
df.mdf1=df.mdf1 %>% mutate(md=factor(md,levels=c("nor","feaw","feai"),labels=c("Normative","SS (fixed-window)","SS (intervention-based)")))
# Sys.time()-t0#Time difference of 4.865639 mins
# save(df.mdf1,file="df.mdf1.Rda")
# loac("df.mdf1.Rda")
```

```{r}
summarySE(df.f1,measurevar = "f1",groupvars = c("mycondition","state"),na.rm=T)%>% 
  ggplot(aes(x=state,y=f1))+
  facet_wrap(~mycondition, labeller=as_labeller(c(regular="Regular",irregular="Irregular")))+
  geom_bar(stat="identity",color="black",fill="white",position=position_dodge(.9))+
  geom_errorbar(aes(ymin = f1-ci,ymax = f1+ci),width=0,size=0.8,position=position_dodge(.9))+
  # geom_jitter(data=df.f1,aes(x=state,y=f1),color=scales::alpha("black",.1))+
  geom_line(data=df.mdf1,aes(x=state,y=f1,color=md,group=md),size=0.8)+
  xlab("Ground truth")+
  scale_x_discrete(labels=c("Generative","Non-causal","Preventative"))+
  ylab("F1-score")+
  scale_color_manual(values=c("#806001","#cc9802","#fdcb39"))+
  theme_bw()+  
  theme(text = element_text(size=12),
    axis.text=element_text(colour="black"),
    strip.text.x = element_text(size = 12),
    panel.grid = element_blank(),
    strip.background =element_rect(fill="white",color="white"),
    legend.position = "bottom",legend.title=element_blank())+
  theme(axis.title.x = element_text(margin = margin(t = 10, r = 0, b = 0, l = 0)),
        legend.margin=margin(-5,0,0,0))

ggsave(file="f_exp_f1.pdf",width = 6.5,height = 5)

# summarySE(df.f1,measurevar = "rec",groupvars = c("mycondition","state"),na.rm=T)%>% 
#   ggplot(aes(x=state,y=rec))+
#   facet_wrap(~mycondition)+
#   geom_bar(stat="identity",color="black",fill="white",position=position_dodge(.9))+
#   geom_errorbar(aes(ymin = rec-ci,ymax = rec+ci),width=0,size=0.8,position=position_dodge(.9))+
#   geom_line(data=df.mdf1,aes(x=state,y=rec,color=md,group=md))+
#   scale_color_manual(values=scales::alpha(c("#7cae00","#00bfc4","#c77cff"),.6))+
#   theme_bw()
# 
# summarySE(df.f1,measurevar = "pre",groupvars = c("mycondition","state"),na.rm=T)%>% 
#   ggplot(aes(x=state,y=pre))+
#   facet_wrap(~mycondition)+
#   geom_bar(stat="identity",color="black",fill="white",position=position_dodge(.9))+
#   geom_errorbar(aes(ymin = pre-ci,ymax = pre+ci),width=0,size=0.8,position=position_dodge(.9))+
#   geom_line(data=df.mdf1,aes(x=state,y=pre,color=md,group=md),size=.7)+
#   scale_color_manual(values=scales::alpha(c("#7cae00","#00bfc4","#c77cff"),.6))+
#   theme_bw()
```

##paired
```{r}
df.pairACC=df.comb %>% mutate(pro=A_pro,paired=B_pro,acc=acc_a)%>%
  rbind(df.comb %>% mutate(pro=B_pro,paired=A_pro,acc=acc_b))

df.pairACC.wide=df.pairACC %>% reshape2:: dcast(subject+mycondition+exp~ paired,value.var = "acc",fun=mean) %>% rename(replace = c("G" = "P1","N" = "P2","P" ="P3"))

df.pairACC.wide %>% 
  MANOVA(dvs="P1:P3", dvs.pattern="P(.)",between=c("mycondition"),within=c("P")) %>%
  EMMEANS("P",by="mycondition")

# lmer(acc~paired+(1|subject)+(1|uni_seed),subset(df.pairACC,mycondition=="regular"))%>%summary()
# lmer(acc~paired+(1|subject)+(1|uni_seed),subset(df.pairACC,mycondition=="irregular"))%>%summary()
```

```{r}
df.pairMdACC=data.frame()
for (k in 1:length(md.sim)){
  df=data.frame(md=names(md.sim)[k],
    mycondition=factor(c("regular","irregular"),levels = c("regular","irregular")),
    paired=rep(c("G","N","P"),each=2)
  )
  for (m in 1:nrow(df)){
    d1=md.sim[[k]] %>% subset(mycondition==as.character(df$mycondition[m]))
    d=d1%>%mutate(paired=B_pro,acc=A_pro==A_state)%>%
      rbind(d1%>%mutate(paired=A_pro,acc=B_pro==B_state))%>%
      subset(paired==df$paired[m])
    df$acc[m]=mean(d$acc)
  }
  df.pairMdACC=rbind(df.pairMdACC,df)
}
df.pairMdACC=df.pairMdACC %>%
  mutate(md=factor(md,levels=c("nor","feaw","feai"),
         labels=c("Normative","SS (fixed-window)","SS (intervention-based)")))
# save(df.pairMdACC,file="df.pairMdACC.Rda")
# load("df.pairMdACC.Rda")
```

```{r}
pic=summarySE(df.pairACC,measurevar = "acc",groupvars = c("paired","mycondition","subject"))

summarySE(pic,measurevar = "acc",groupvars = c("paired","mycondition"))%>%
  ggplot(aes(x=paired,y=acc))+
  facet_wrap(~mycondition,labeller=as_labeller(c(regular="Regular",irregular="Irregular")))+
  geom_bar(stat="identity",color="black",fill="white",position=position_dodge(.9))+
  # geom_jitter(data=pic,aes(x=paired,y=acc),color=scales::alpha("black",.1),height = 0.1)+
  geom_errorbar(aes(ymin = acc-ci,ymax = acc+ci),width=0,size=0.8,position=position_dodge(.9))+
  geom_line(data=df.pairMdACC,aes(x=paired,y=acc,color=md,group=md),size=.8)+
  xlab("Ground truth of the paired link")+
  scale_x_discrete(labels=c("Generative","Non-causal","Preventative"))+
  ylab("Accuracy")+
  scale_color_manual(values=c("#806001","#cc9802","#fdcb39"))+
  theme_bw()+  
  theme(text = element_text(size=12),
  axis.text=element_text(colour="black"),
  strip.text.x = element_text(size = 12),
  panel.grid = element_blank(),
  strip.background =element_rect(fill="white",color="white"),
  legend.position = "bottom",legend.title=element_blank())+
  theme(axis.title.x = element_text(margin = margin(t = 10, r = 0, b = 0, l = 0)),
    legend.margin=margin(-5,0,0,0))

ggsave(file="f_exp_paired.pdf",width = 6.5,height = 5)
```

##link f1-pair
```{r}
df.link=df.comb %>% mutate(pro=A_pro,state=A_state,paired=B_pro)%>%
  rbind(df.comb %>% mutate(pro=B_pro,state=B_state,paired=A_pro))

df.pairF1=data.frame() 
for (k in unique(df.comb$uni_seed)){
  df=data.frame(uni_seed=k,paired_pro=rep(c("G","N","P"),each=3),state=rep(c("G","N","P"),3),f1=NA)
  df=rbind(mutate(df,mycondition="regular"),mutate(df,mycondition="irregular"))%>%
    mutate(mycondition=factor(mycondition,levels = c("regular","irregular")))
  
  for (m in 1:nrow(df)){
    d=df.link%>% subset(uni_seed==k & paired==df$paired_pro[m] & mycondition==df$mycondition[m])
    re=myF1(d,df$state[m])
    df$rec[m]=re[[1]];df$pre[m]=re[[2]];df$f1[m]=re[[3]]
  }
  df.pairF1=rbind(df.pairF1,df)
}

df.pairF1.wide=df.pairF1 %>% reshape2:: dcast(uni_seed+mycondition~ state+paired_pro,value.var = "f1")%>% rename(replace = c("G_G" = "S1P1","G_N" = "S1P2","G_P" ="S1P3","N_G" = "S2P1","N_N" = "S2P2","N_P" ="S2P3","P_G" = "S3P1","P_N" = "S3P2","P_P" ="S3P3"))

df.pairF1.wide %>%
  subset(mycondition=="regular")%>%
  MANOVA(dvs="S1P1:S3P3", dvs.pattern="S(.)P(.)",within=c("S","P"))

df.pairF1.wide %>%
  subset(mycondition=="irregular")%>%
  MANOVA(dvs="S1P1:S3P3", dvs.pattern="S(.)P(.)",within=c("S","P"))
```

```{r eval = FALSE, echo = FALSE}
df.pairMdf1=data.frame()
for (k in 1:length(md.sim)){
    df=data.frame(md=names(md.sim)[k],paired_pro=rep(c("G","N","P"),each=3),state=rep(c("G","N","P"),3),f1=NA)
    df=rbind(mutate(df,mycondition="regular"),mutate(df,mycondition="irregular"))%>%
    mutate(mycondition=factor(mycondition,levels = c("regular","irregular")))

  for (m in 1:nrow(df)){
    d1=md.sim[[k]] %>% subset(mycondition==as.character(df$mycondition[m]))
    d=d1%>%mutate(pro=A_pro,state=A_state,paired=B_pro)%>%
      rbind(d1%>%mutate(pro=B_pro,state=B_state,paired=A_pro)) %>%
      subset(paired==df$paired_pro[m])
    re=myF1(d,df$state[m])
    df$rec[m]=re[[1]];df$pre[m]=re[[2]];df$f1[m]=re[[3]]
  }
  df.pairMdf1=rbind(df.pairMdf1,df)
}
df.pairMdf1=df.pairMdf1 %>% mutate(md=factor(md,levels=c("nor","feai","feaw"),labels=c("Normative","SS (fixed-window)","SS (intervention-based)")))
```

```{r}
summarySE(df.pairF1,measurevar = "f1",groupvars = c("mycondition","state","paired_pro"),na.rm=T)%>% 
  ggplot(aes(x=state,y=f1,group=paired_pro,fill=paired_pro))+
  geom_bar(stat="identity",color="black",fill="white",position=position_dodge(.9))+
  geom_errorbar(aes(ymin = f1-ci,ymax = f1+ci),width=0,size=0.8,position=position_dodge(.9),color="black")+
  # geom_point(data=df.pairMdf1,aes(x=state,y=f1,color=md,group=paired_pro),position=position_dodge(.9))+
  facet_wrap(~mycondition,labeller=as_labeller(c(regular="Regular",irregular="Irregular")))+
  # scale_color_manual(values=scales::alpha(c("#7cae00","#00bfc4","#c77cff"),.6))+
  xlab("Ground truth")+
  scale_x_discrete(labels=c("Generative","Non-causal","Preventative"))+
  ylab("F1-score")+
  # scale_fill_manual("Paired with",values=c("#66A61E","#666666","#E6AB02"),labels=c("Generative","Non-causal","Preventative"))+
  theme_bw()+  
  theme(text = element_text(size=12),
  axis.text=element_text(colour="black"),
  strip.text.x = element_text(size = 12),
  panel.grid = element_blank(),
  strip.background =element_rect(fill="white",color="white"),
  legend.position = "bottom")+
  theme(axis.title.x = element_text(margin = margin(t = 10, r = 0, b = 0, l = 0)),
        axis.text.x = element_text(margin = margin(t = 17, r = 0, b = 0, l = 0)),
        axis.ticks.x = element_blank(),
    legend.margin=margin(-5,0,0,0))

ggsave(file="exp_pairedF1.pdf",width = 8,height = 3.8)

```
###pair-frequency (w/o gd)
```{r}
myPairFrePlot<-function(df){
  df%>% ggplot(aes(x=paired,fill=state))+
  facet_wrap(~mycondition,labeller=as_labeller(c(regular="Regular",irregular="Irregular")))+
  geom_bar(position = "fill",color="black",size=0.2,width=0.5)+
  # geom_hline(yintercept = c(1/3,2/3),linetype = 'dotted')+
    scale_fill_manual("Choice",values=c("#66A61E","#666666","#E6AB02"),labels=c("Generative","Non-causal","Preventative"))+
  theme_bw()+
    theme(text = element_text(size=12),
  axis.text=element_text(colour="black"),
  panel.grid = element_blank(),
  strip.background =element_rect(fill="white",color="white"))+
  theme(axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank())
}

df.comb %>% mutate(paired=B_pro,state=A_state,gd=A_pro)%>%
  rbind(mutate(df.comb,paired=A_pro,state=B_state,gd=B_pro))%>%
  myPairFrePlot()+
  ylab("Proportion")+
  theme(legend.position ="right")

```


###pair-frequency
```{r }
myPairFrePlotGd<-function(df){
  df%>% ggplot(aes(x=interaction(paired,gd),fill=state))+
  facet_wrap(~mycondition,labeller=as_labeller(c(regular="Regular",irregular="Irregular")))+
  geom_bar(position = "fill",color="black",size=0.2,width=0.5)+
  # geom_hline(yintercept = c(1/3,2/3),linetype = 'dotted')+
    scale_fill_manual("Choice",values=c("#66A61E","#666666","#E6AB02"),labels=c("Generative","Non-causal","Preventative"))+
  theme_bw()+
    theme(text = element_text(size=12),
  axis.text=element_text(colour="black"),
  panel.grid = element_blank(),
  strip.background =element_rect(fill="white",color="white"))+
  theme(axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank())
}

df.comb %>% mutate(paired=B_pro,state=A_state,gd=A_pro)%>%
  rbind(mutate(df.comb,paired=A_pro,state=B_state,gd=B_pro))%>%
  myPairFrePlotGd()+
  ylab("Proportion")+
  theme(legend.position ="right")

ggsave(file="exp_frequency_human.pdf",width = 9,height = 3.3)

md.sim[["nor"]] %>% mutate(paired=B_pro,state=A_state,gd=A_pro)%>%
  rbind(mutate(md.sim[["nor"]],paired=A_pro,state=B_state,gd=B_pro))%>%
  myPairFrePlotGd()+
  theme(text = element_text(size=8),
        strip.text.x = element_text(size = 8),
        axis.title.y = element_blank(),legend.position ="none")

ggsave(file="exp_frequency_nor.pdf",width =3.6,height = 1.6)

md.sim[["feaw"]] %>% mutate(paired=B_pro,state=A_state,gd=A_pro)%>%
  rbind(mutate(md.sim[["feaw"]],paired=A_pro,state=B_state,gd=B_pro))%>%
  myPairFrePlotGd()+
  theme(text = element_text(size=6),
      strip.text.x = element_text(size = 8),
      axis.title.y = element_blank(),legend.position ="none",
      axis.ticks.y = element_blank())

ggsave(file="exp_frequency_feaw.pdf",width =3.6,height = 1.6)


md.sim[["feai"]] %>% mutate(paired=B_pro,state=A_state,gd=A_pro)%>%
  rbind(mutate(md.sim[["feai"]],paired=A_pro,state=B_state,gd=B_pro))%>%
  myPairFrePlotGd()+
  theme(text = element_text(size=6),
      strip.text.x = element_text(size = 8),
      axis.title.y = element_blank(),legend.position ="none",
      axis.ticks.y = element_blank())

ggsave(file="exp_frequency_feai.pdf",width =3.6,height = 1.6)
```

```{r}
df=df.comb %>% mutate(paired=B_pro,state=A_state,gd=A_pro)%>%
  rbind(mutate(df.comb,paired=A_pro,state=B_state,gd=B_pro))
write.csv(df,file="multinom.csv",row.names = F)
```

```{r}
summarySE(df.f1,measurevar = "rec",groupvars = c("state","mycondition"))
t.test(rec~mycondition,df.f1[df.f1$state=="P",],var.equal = T)
df.f1.1=df.f1[df.f1$state=="P",]
cohen.d(df.f1.1$rec,df.f1.1$mycondition)
t.test(rec~mycondition,df.f1[df.f1$state=="N",])
t.test(rec~mycondition,df.f1[df.f1$state=="G",])
```

#order effect
```{r}
df.ordACC=df.comb %>% mutate(pro=A_pro,ord=order_a,acc=acc_a)%>%
  rbind(df.comb %>% mutate(pro=B_pro,ord=order_b,acc=acc_b))

df.ordACC.wide=df.ordACC %>% reshape2:: dcast(subject+mycondition+exp~ ord,value.var = "acc",fun=mean)%>% rename(replace = c("0" = "L1","1" = "L2","2" ="L3"))


df.ordACC.wide %>% 
  MANOVA(dvs="L1:L3", dvs.pattern="L(.)",between=c("mycondition"),within=c("L")) %>%
  EMMEANS("L")
```


```{r}
#add large sample of stimuli
load("mdall_sim.Rda")
mdall=subset(mdall,!(seed%in% mdall$seed[which(rowSums(is.na(mdall)) > 0)]))

mdall=mdall %>% mutate(A_pro=substr(trial_type,1,1),
                       B_pro=substr(trial_type,2,2),
                       A_state=substr(choice,1,1),
                       B_state=substr(choice,2,2))

mdname=c("fea_i","fea_w4","nor")
df.simLargeACC=data.frame()
for (k in mdname){
    df=data.frame(md=paste(k,"large",sep="_"),
    mycondition=factor(c("regular","irregular"),levels = c("regular","irregular")),
    ord=rep(c(0,1,2),each=2))
    
    for (m in 1:nrow(df)){
      d1=mdall %>% subset(mycondition==as.character(df$mycondition[m]))
      d1$acc=d1[,k]
      
      a_acc=d1%>% subset(order_a==df$ord[m] & A_pro==A_state) %>% 
        group_by(uni_label) %>% dplyr:: summarise(acc=sum(acc))
      b_acc=d1%>% subset(order_b==df$ord[m] & B_pro==B_state)%>% 
        group_by(uni_label) %>% dplyr:: summarise(acc=sum(acc))
    
      
      df$acc[m]=mean(c(a_acc$acc,b_acc$acc))
    }
    df.simLargeACC=rbind(df.simLargeACC,df)
}
```

```{r}
df.ordMdACC=data.frame()
for (k in 1:length(md.sim)){
  df=data.frame(md=names(md.sim)[k],
    mycondition=factor(c("regular","irregular"),levels = c("regular","irregular")),
    ord=rep(c(0,1,2),each=2)
  )
  for (m in 1:nrow(df)){
    d1=md.sim[[k]] %>% subset(mycondition==as.character(df$mycondition[m]) & (order_a == df$ord[m] |  order_b == df$ord[m]))
    d=d1%>%mutate(ord=order_a,acc=acc_a)%>%
      rbind(d1%>%mutate(ord=order_b,acc=acc_b))%>%
      subset(ord==df$ord[m])
    df$acc[m]=mean(d$acc)
  }
  df.ordMdACC=rbind(df.ordMdACC,df)
}

df.ordMdACCcomb=rbind(df.ordMdACC,df.simLargeACC)

df.ordMdACCcomb=df.ordMdACCcomb%>%
  mutate(md=factor(md,levels=c("nor","nor_large","feaw","fea_w4_large","feai","fea_i_large"),
         labels=c("Normative", "Normative (large)","SS (fixed-window)","SS (fixed-window) (large)",
                  "SS (intervention-based)","SS (intervention-based) (large)")))
```

```{r}
pic=summarySE(df.ordACC,measurevar = "acc",groupvars = c("ord","mycondition","subject"))

summarySE(pic,measurevar = "acc",groupvars = c("ord","mycondition"))%>%
  ggplot(aes(x=ord,y=acc))+
  facet_wrap(~mycondition,labeller=as_labeller(c(regular="Regular",irregular="Irregular")))+
  geom_bar(stat="identity",color="black",fill="white",position=position_dodge(.9))+
  # geom_jitter(data=pic,aes(x=paired,y=acc),color=scales::alpha("black",.1),height = 0.1)+
  geom_errorbar(aes(ymin = acc-ci,ymax = acc+ci),width=0,size=0.8,position=position_dodge(.9))+
  geom_line(data=df.ordMdACCcomb,aes(x=ord,y=acc,color=md,group=md,linetype=md),size=.8)+
  scale_color_manual(values=c("#806001",scales::alpha("#806001",.9),"#cc9802",scales::alpha("#cc9802",.9),
                                "#fdcb39",scales::alpha("#fdcb39",.9)))+
  scale_linetype_manual(values=c("solid","dashed","solid","dashed","solid","dashed"))+
  xlab("Intervention order")+
  scale_x_continuous(breaks = c(0,1,2),labels=c("Level 0","Level 1","Level 2"))+
  ylab("Accuracy")+
  theme_bw()+  
  theme(text = element_text(size=12),
  axis.text=element_text(colour="black"),
  strip.text.x = element_text(size = 12),
  panel.grid = element_blank(),
  strip.background =element_rect(fill="white",color="white"),
  legend.position = "bottom",legend.title=element_blank())+
  theme(axis.title.x = element_text(margin = margin(t = 10, r = 0, b = 0, l = 0)),
    legend.margin=margin(-5,0,0,0))

# ggsave(file="f_exp_ord.pdf",width = 6.5,height = 5)

ggsave(file="f_exp_ord.pdf",width = 6.5,height = 5)
```

```{r}
tmp=df.comb %>% mutate(state=A_state,gd=A_pro,ord=as.factor(order_a),acc=acc_a)%>%
  rbind(mutate(df.comb,state=B_state,gd=B_pro,ord=as.factor(order_b),acc=acc_b))%>%
  summarySE(measurevar = "acc", groupvars = c("gd","ord","subject","mycondition"))

tmp2=df.comb %>% mutate(state=A_state,gd=A_pro,ord=as.factor(order_a),acc=acc_a)%>%
  rbind(mutate(df.comb,state=B_state,gd=B_pro,ord=as.factor(order_b),acc=acc_b))%>%
  summarySE(measurevar = "acc", groupvars = c("gd","ord","subject","mycondition"))%>%
  reshape2:: dcast(subject+mycondition~ ord+gd,value.var = "acc",fun=mean)%>% 
  rename(replace = c("0_G" = "L1G1","0_N" = "L1G2","0_P" = "L1G3",
                     "1_G" = "L2G1","1_N" = "L2G2","1_P" = "L2G3",
                     "2_G" = "L3G1","2_N" = "L3G2","2_P" = "L3G3"))
  
tmp2 %>% 
  MANOVA(dvs="L1G1:L3G3", dvs.pattern="L(.)G(.)",between=c("mycondition"),within=c("L","G")) %>%
  EMMEANS("L",by="G")

0.05/6

tmp%>%subset(mycondition=="regular" & gd=="G")
aov(acc~ord,tmp%>%subset(mycondition=="regular" & gd=="G")) %>% summary()

```

```{r}
df.comb %>% mutate(state=A_state,gd=A_pro,ord=as.factor(order_a))%>%
  rbind(mutate(df.comb,state=B_state,gd=B_pro,ord=as.factor(order_b)))%>%
  ggplot(aes(x=ord,fill=state))+
  facet_grid(cols=vars(gd),rows=vars(mycondition),labeller=as_labeller(c(regular="Regular",irregular="Irregular",G="Generative",N="Non-causal",P="Preventative")))+
  geom_bar(position = "fill",color="black",size=0.2,width=0.5)+
  scale_fill_manual("Choice",values=c("#66A61E","#666666","#E6AB02"),
                    labels=c("Generative","Non-causal","Preventative")
                    )+
  theme_classic()+
  ylab("Proportion")+
  xlab("Intervention order")+
  scale_x_discrete(breaks = c(0,1,2),labels=c("Level 0","Level 1","Level 2"))+
  theme(text = element_text(size=12),
  axis.text=element_text(colour="black"),
  panel.grid = element_blank(),
  strip.background =element_rect(fill="white",color="black" ),
  strip.placement = "outside")

ggsave(file="exp_order_human.pdf",width = 9,height = 4)
```

```{r}
myOrdMDPlot<-function(df){
  df1=df%>%
    mutate(paired=B_pro,state=A_state,gd=A_pro,ord=order_a)%>%
    group_by(gd,state,paired,seed,mycondition,ord)%>%
    dplyr::summarise(acc=sum(acc))%>%
    group_by(gd,state,mycondition,ord)%>%
    dplyr::summarise(acc=mean(acc))
  
  df2=df%>%
    mutate(paired=A_pro,state=B_state,gd=B_pro,ord=order_b)%>%
    group_by(gd,state,paired,seed,mycondition,ord)%>%
    dplyr::summarise(acc=sum(acc))%>%
    group_by(gd,state,mycondition,ord)%>%
    dplyr::summarise(acc=mean(acc))
  
  rbind(df1,df2)%>%
    summarySE(measurevar = "acc",groupvars = c("gd","state","mycondition","ord"))%>%
    mutate(ord=factor(ord),mycondition=factor(mycondition,levels = c("regular","irregular"))) %>%
    ggplot(aes(x=ord,y=acc,fill=state))+
    facet_grid(cols=vars(gd),rows=vars(mycondition),labeller=as_labeller(c(regular="Regular",irregular="Irregular",G="Generative",N="Non-causal",P="Preventative")))+
    geom_bar(stat="identity",color="black",size=0.2,width=0.5)+
    # geom_hline(yintercept = c(1/3,2/3),linetype = 'dotted')+
    scale_fill_manual(values=c("#66A61E","#666666","#E6AB02"))+
  theme_classic()+
    scale_x_discrete(breaks = c(0,1,2),labels=c("L0","L1","L2"))+
    theme(text = element_text(size=12),
          strip.text.x = element_text(margin = margin(3,3,3,3)),
          strip.text.y = element_text(margin = margin(3,3,3,3)),
          axis.title = element_blank(),
          axis.text=element_text(colour="black"),
          panel.grid = element_blank(),
          strip.background =element_rect(fill="white",color="black",),
          legend.position = "none",
          strip.placement = "outside")
}

#normative
mdall%>% mutate(acc=nor)%>% 
  myOrdMDPlot()

ggsave(file="exp_order_nor.pdf",width =5.5,height = 4)

#feai
mdall%>% mutate(acc=fea_w4)%>% 
  myOrdMDPlot()+
  theme(axis.ticks.y = element_blank())
  
ggsave(file="exp_order_feaw.pdf",width =5.5,height = 4)

#feai
mdall%>% mutate(acc=fea_i)%>% 
  myOrdMDPlot()+
  theme(axis.ticks.y = element_blank())

ggsave(file="exp_order_feai.pdf",width =5.5,height = 4)


```

